services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - php
      - mediamtx

  php:
    build:
      context: .
      dockerfile: Dockerfile.php
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD:-root}"
      MYSQL_DATABASE: "${MYSQL_DATABASE:-appdb}"
      MYSQL_USER: "${MYSQL_USER:-appuser}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD:-apppass}"
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_AUTH_TYPE: cookie
    ports:
      - "8080:80"
    depends_on:
      - mysql

  mediamtx:
    image: bluenviron/mediamtx:latest
    ports:
      - "1935:1935"
      - "8554:8554"
      - "8888:8888"
    volumes:
      - ./mediamtx/mediamtx.json:/mediamtx.json:ro

volumes:
  db_data:
  tailwind_node_modules: